version: "2"
services:
  tianguix:
    build: .
    ports:
      - "8080"
    environment:
      - DB_HOST=mongo
      - ASSET_HOST=asset-tianguix
      - ASSET_PORT=8080
      - APM_ADDRESS=169.254.141.109
    networks: 
      - tianguix-net
      - default
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - tianguix
    ports:
      - "80:4000"
networks: 
  tianguix-net:
    driver: bridge
