version: "2"
services:
  web:
    build: .
    ports:
      - "8080:3000"
    environment:
      - DB_HOST=mongo
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"