version: "2"
services:
  tianguix:
    build: .
    ports:
      - "8080"
    environment:
      - DB_HOST=mongo
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - tianguix
    ports:
      - "8080:4000"