version: '2'

services:
  asset-tianguix:
    image: asset-tianguix:latest
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /data/springboot-docker-compose-app
    ports:
      - "8090:8080"
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_USER: uniandes
      MYSQL_PASS: seneca
      MYSQL_DB: dgsit
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: dgsit
      MYSQL_USER: uniandes
      MYSQL_PASSWORD: seneca
      MYSQL_ROOT_PASSWORD: root
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

# Join external networks https://docs.docker.com/compose/networking/#use-a-pre-existing-network
networks: 
  default:
    external: 
      name: tianguix_tianguix-net